### ISSUE TITLE
Alpine Linux (OpenRC) Support

### ISSUE THREAD

**Issue by sussycatgirl** [Jan0660/JanD#4]
![image](https://user-images.githubusercontent.com/26145882/140183688-8807f350-d030-4127-83ea-558ebe2837cd.png)

JanD should be able to create an OpenRC service file.

Example file (/etc/init.d/jand-jan or whatever):
```
#!/sbin/openrc-run

name="The Jan Process Manager"
command="/usr/bin/jand"
command_args="start-service"
pidfile="/idk/for/example/tmp/jand.pid"
command_user="1000:1000"
```
(No idea if this works)

For this to work, jand must first be able to create a pid file which OpenRC can access (`pidfile="/idk/for/example/tmp/jand.pid"` needs to point to that file).

**Comment by Jan0660** [comment]
Implemented in https://github.com/Jan0660/JanD/commit/332059f75dda67faff8c6b458b13bbcee0b1924f.

**Comment by sussycatgirl** [comment]
based
